In [1]:
import sys
sys.path.append(rf"/Users/baia/Desktop/PYTHON/mba_dsa_usp_esalq")

from TCC.utils.constantes import *

In [13]:
df_coinbase_premium_semanal = pd.read_csv(rf"/Users/baia/Desktop/PYTHON/mba_dsa_usp_esalq/TCC/data/dados_btc/raw/201708_coinbase_premium_btc_v2_semanal.csv")
df_coinbase_premium_diario = pd.read_csv(rf"/Users/baia/Desktop/PYTHON/mba_dsa_usp_esalq/TCC/data/dados_btc/raw/201805_coinbase_premium_btc_v2_diario.csv")
# df_in_out_flow['Data_UTC'] = pd.to_datetime(df_in_out_flow['Date'], utc=True,).dt.strftime("%Y-%m-%d")
df_coinbase_premium_semanal['Data_UTC'] = pd.to_datetime(df_coinbase_premium_semanal['time'], utc=True).dt.strftime("%Y-%m-%d")
df_coinbase_premium_diario['Data_UTC'] = pd.to_datetime(df_coinbase_premium_diario['time'], utc=True).dt.strftime("%Y-%m-%d")
df_coinbase_premium_semanal['Data_UTC'] = pd.to_datetime(df_coinbase_premium_semanal['Data_UTC'])
df_coinbase_premium_diario['Data_UTC'] = pd.to_datetime(df_coinbase_premium_diario['Data_UTC'])

In [17]:
display(df_coinbase_premium_semanal[['Data_UTC','Premium (%)']].head(3))
display(df_coinbase_premium_diario[['Data_UTC','Premium (%)']].head(3))

df_cb_semanal = (df_coinbase_premium_semanal[['Data_UTC','Premium (%)']]
                 .rename(columns={'Premium (%)':'premium_semanal'})
                 )

df_cb_diario = (df_coinbase_premium_diario[['Data_UTC','Premium (%)']]
                 .rename(columns={'Premium (%)':'premium_diario'})
                 )

    Data_UTC  Premium (%)
0 2017-08-14    -0.863864
1 2017-08-21     0.698374
2 2017-08-28     2.594099

    Data_UTC  Premium (%)
0 2018-04-14     0.051256
1 2018-04-15     0.002992
2 2018-04-16    -0.198266

In [18]:
display(DF_ERA_VAREJO
 
 .merge(df_cb_semanal, how='left', on='Data_UTC')
 .merge(df_cb_diario, how='left', on='Data_UTC')
 
)

display(DF_ERA_INSTITUCIONAL
 
 .merge(df_cb_semanal, how='left', on='Data_UTC')
 .merge(df_cb_diario, how='left', on='Data_UTC')
 
)

       Data_UTC     era  premium_semanal  premium_diario
0    2017-01-01  varejo              NaN             NaN
1    2017-01-02  varejo              NaN             NaN
2    2017-01-03  varejo              NaN             NaN
3    2017-01-04  varejo              NaN             NaN
4    2017-01-05  varejo              NaN             NaN
...         ...     ...              ...             ...
1161 2020-03-07  varejo              NaN        0.165529
1162 2020-03-08  varejo              NaN        0.055394
1163 2020-03-09  varejo        -0.297502        0.058639
1164 2020-03-10  varejo              NaN        0.001520
1165 2020-03-11  varejo              NaN        0.044489

[1166 rows x 4 columns]

       Data_UTC            era  premium_semanal  premium_diario
0    2020-03-11  institucional              NaN        0.044489
1    2020-03-12  institucional              NaN        1.189583
2    2020-03-13  institucional              NaN        1.057613
3    2020-03-14  institucional              NaN       -0.131669
4    2020-03-15  institucional              NaN       -0.297502
...         ...            ...              ...             ...
1965 2025-07-28  institucional         0.006068        0.007005
1966 2025-07-29  institucional              NaN       -0.014726
1967 2025-07-30  institucional              NaN       -0.008613
1968 2025-07-31  institucional              NaN       -0.002548
1969 2025-08-01  institucional              NaN       -0.043425

[1970 rows x 4 columns]

## GETTING BINANCE DATA FOR BTCUSDT PAIR

In [14]:
from binance.client import Client

client = Client(API_KEY, API_SECRET)

# Define the symbol for BTC/USDT pair
symbol = 'BTCUSDT'

# Define custom start and end time
start_time = datetime.datetime(2017, 1, 1, 0, 0, 0)
end_time = datetime.datetime(2025, 8, 1, 0, 0, 0)

klines = client.get_historical_klines(symbol=symbol, interval=Client.KLINE_INTERVAL_1DAY, start_str=str(start_time), end_str=str(end_time),)

# Convert the data into a pandas dataframe for easier manipulation
df_btcusdt = pd.DataFrame(klines, columns=['Open Time', 'Open', 'High', 'Low', 'Close', 'Volume', 'Close Time', 'Quote Asset Volume', 'Number of Trades', 'Taker Buy Base Asset Volume', 'Taker Buy Quote Asset Volume', 'Ignore'])


columns_to_convert = ['Open', 'High', 'Low', 'Close', 'Volume', 'Quote Asset Volume', 'Number of Trades', 'Taker Buy Base Asset Volume', 'Taker Buy Quote Asset Volume']

for col in columns_to_convert:
    df_btcusdt[col] = df_btcusdt[col].astype(float)

df_btcusdt

,Open Time,Open,High,Low,Close,Volume,Close Time,Quote Asset Volume,Number of Trades,Taker Buy Base Asset Volume,Taker Buy Quote Asset Volume,Ignore
0,1502928000000,4261.48,4485.39,4200.74,4285.08,795.150377,1503014399999,3.454770e+06,3427.0,616.248541,2.678216e+06,0
1,1503014400000,4285.08,4371.52,3938.77,4108.37,1199.888264,1503100799999,5.086958e+06,5233.0,972.868710,4.129123e+06,0
2,1503100800000,4108.37,4184.69,3850.00,4139.98,381.309763,1503187199999,1.549484e+06,2153.0,274.336042,1.118002e+06,0
3,1503187200000,4120.98,4211.08,4032.62,4086.29,467.083022,1503273599999,1.930364e+06,2321.0,376.795947,1.557401e+06,0
4,1503273600000,4069.13,4119.62,3911.79,4016.00,691.743060,1503359999999,2.797232e+06,3972.0,557.356107,2.255663e+06,0
...,...,...,...,...,...,...,...,...,...,...,...,...
2902,1753660800000,119415.56,119800.00,117427.50,118062.32,13961.747540,1753747199999,1.655882e+09,1824777.0,7224.917740,8.571284e+08,0
2903,1753747200000,118062.32,119273.36,116950.75,117950.76,15137.934450,1753833599999,1.788682e+09,1956694.0,7988.937360,9.441628e+08,0
2904,1753833600000,117950.75,118792.00,115796.23,117840.30,15586.736310,1753919999999,1.832697e+09,1997369.0,7803.614340,9.176329e+08,0
2905,1753920000000,117840.29,118922.45,115500.00,115764.08,17010.007300,1754006399999,2.002870e+09,1859532.0,8313.516160,9.795194e+08,0
2906,1754006400000,115764.07,116052.00,112722.58,113297.93,24487.102060,1754092799999,2.810269e+09,4160829.0,11487.221200,1.318593e+09,0

In [15]:
df_btcusdt['Data_UTC'] = pd.to_datetime(df_btcusdt['Open Time'], unit='ms').dt.strftime("%Y-%m-%d")
df_btcusdt['Data_UTC'] = pd.to_datetime(df_btcusdt['Data_UTC'])
df_btcusdt

,Open Time,Open,High,Low,Close,Volume,Close Time,Quote Asset Volume,Number of Trades,Taker Buy Base Asset Volume,Taker Buy Quote Asset Volume,Ignore,Data_UTC
0,1502928000000,4261.48,4485.39,4200.74,4285.08,795.150377,1503014399999,3.454770e+06,3427.0,616.248541,2.678216e+06,0,2017-08-17
1,1503014400000,4285.08,4371.52,3938.77,4108.37,1199.888264,1503100799999,5.086958e+06,5233.0,972.868710,4.129123e+06,0,2017-08-18
2,1503100800000,4108.37,4184.69,3850.00,4139.98,381.309763,1503187199999,1.549484e+06,2153.0,274.336042,1.118002e+06,0,2017-08-19
3,1503187200000,4120.98,4211.08,4032.62,4086.29,467.083022,1503273599999,1.930364e+06,2321.0,376.795947,1.557401e+06,0,2017-08-20
4,1503273600000,4069.13,4119.62,3911.79,4016.00,691.743060,1503359999999,2.797232e+06,3972.0,557.356107,2.255663e+06,0,2017-08-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2902,1753660800000,119415.56,119800.00,117427.50,118062.32,13961.747540,1753747199999,1.655882e+09,1824777.0,7224.917740,8.571284e+08,0,2025-07-28
2903,1753747200000,118062.32,119273.36,116950.75,117950.76,15137.934450,1753833599999,1.788682e+09,1956694.0,7988.937360,9.441628e+08,0,2025-07-29
2904,1753833600000,117950.75,118792.00,115796.23,117840.30,15586.736310,1753919999999,1.832697e+09,1997369.0,7803.614340,9.176329e+08,0,2025-07-30
2905,1753920000000,117840.29,118922.45,115500.00,115764.08,17010.007300,1754006399999,2.002870e+09,1859532.0,8313.516160,9.795194e+08,0,2025-07-31
2906,1754006400000,115764.07,116052.00,112722.58,113297.93,24487.102060,1754092799999,2.810269e+09,4160829.0,11487.221200,1.318593e+09,0,2025-08-01

In [16]:
df_btcusdt.to_csv(rf"/Users/baia/Desktop/PYTHON/mba_dsa_usp_esalq/TCC/data/dados_btc/raw/201708_btcusdt_binance.csv", index=False)

In [ ]:
# FAZER LOOP PARA PEGAR OS DADOS DA COINBASE
import requests

start_time2 = datetime.datetime(2017, 1, 1, 0, 0, 0)
end_time2 = datetime.datetime(2017, 10, 1, 0, 0, 0)

# Define start and end times using existing variables
start_timestamp = int(start_time2.timestamp())
end_timestamp = int(end_time2.timestamp())

url = "https://api.exchange.coinbase.com/products/btc-usd/candles"

params = {
    'granularity': 86400,
    'start': start_timestamp,
    'end': end_timestamp
}

response = requests.get(url, params=params)

print(response.text)

[[1506816000,4256.92,4396.99,4339.01,4394.81,5366.91196997],[1506729600,4143.52,4356.28,4156.99,4339,6235.07845604],[1506643200,4015.17,4212.99,4189.42,4156.99,10360.83388071],[1506556800,4122,4269.95,4200,4189.42,7903.94689054],[1506470400,3880.36,4228.39,3885.09,4200,12072.66869574],[1506384000,3854.29,3960,3919.98,3885.09,5893.22353833],[1506297600,3669.01,3969.37,3669.01,3919.78,9583.73758911],[1506211200,3630.01,3789.36,3787.33,3669.01,4692.79090244],[1506124800,3580,3818.89,3619.01,3787.33,6595.93530667],[1506038400,3509.79,3767.77,3617.47,3619.01,12649.02130076],[1505952000,3571,3903.57,3872.07,3617.47,14978.48542601],[1505865600,3850.01,4044,3910.11,3872.06,9910.40111429],[1505779200,3850.44,4125.22,4100,3910.11,13781.15538642],[1505692800,3717.56,4130,3719.98,4100,16906.72338998],[1505606400,3475.64,3841,3726.51,3719.97,11718.88020167],[1505520000,3600,4042.98,3740.02,3726.51,19031.68597217],[1505433600,2975.01,3894.48,3249.99,3740.02,54488.48241948],[1505347200,3230.05,3923,3855.61,3250.4,36363.92501211],[1505260800,3726,4174.53,4164.52,3855.32,22842.53225552],[1505174400,4080,4375.37,4210.72,4164.52,12373.3985777],[1505088000,4111.14,4365,4251.36,4210.72,9068.25507562],[1505001600,4139,4349.99,4334.36,4251.36,10078.69985674],[1504915200,4180,4449.95,4350,4334.36,10073.89558667],[1504828800,4140,4679.99,4624.18,4350,22102.7184586],[1504742400,4475.01,4665.44,4616.18,4624.18,8455.04147983],[1504656000,4431,4692,4432.51,4616.18,16174.30433105],[1504569600,4242.38,4514.95,4498.46,4432.51,17315.43019201],[1504483200,4234.16,4628.05,4626.05,4498.25,20518.88448285],[1504396800,4524,4749.99,4642.39,4626.05,11569.36076538],[1504310400,4500,4980,4948,4649.99,19577.18874549],[1504224000,4706,4948,4743.94,4947.99,16762.80580838],[1504137600,4580.84,4769.03,4581.98,4743.94,13628.46777811],[1504051200,4500.55,4635.21,4599.01,4581.98,10383.4343046],[1503964800,4350,4656.83,4384.99,4599,14509.95812379],[1503878400,4200,4396,4343.5,4384.99,10452.60382073],[1503792000,4309.87,4392,4344.32,4340.11,7041.34420177],[1503705600,4260.01,4374.39,4360,4344.32,6146.47876206],[1503619200,4284.01,4453.9,4312.03,4360,10918.77972836],[1503532800,4112.76,4349.99,4142.5,4312.03,10247.98420911],[1503446400,4058.26,4247.88,4092,4143.49,11746.0041498],[1503360000,3583.46,4145,4002,4092,21922.49731034],[1503273600,3950.88,4089.99,4050.99,4002,12417.65707555],[1503187200,4044.52,4190.21,4157.41,4050.99,8331.87235879],[1503100800,4000,4186.1,4101.72,4157.41,10502.74082464],[1503014400,3960.47,4350,4280.01,4101.72,20823.05141554],[1502928000,4180,4469,4370.01,4280.01,19980.89160504],[1502841600,3928.82,4385.5,4159.93,4370.01,17969.62620634],[1502755200,3807.14,4434.42,4320.53,4159.93,32018.16155552],[1502668800,3985.01,4328,4060.47,4320.6,20059.96196841],[1502582400,3850,4200,3874,4060.47,23522.1419857],[1502496000,3622.87,3974,3656.14,3874,18972.1433559],[1502409600,3416.86,3725,3444.98,3656.15,15315.75236128],[1502323200,3317,3448,3342.8,3444.98,9348.35914865],[1502236800,3232.62,3428.29,3423.28,3342.8,13076.14627076],[1502150400,3349.91,3489,3398.23,3422.43,16014.00638269],[1502064000,3190,3416,3222.22,3398.23,11325.4162028],[1501977600,3150,3278.42,3243.5,3222.22,8666.20078218],[1501891200,2857.34,3335,2857.34,3243.49,21614.60061123],[1501804800,2760,2877.79,2787.05,2857.34,7714.98047973],[1501718400,2699.89,2799,2699.9,2787.02,7425.95745626],[1501632000,2650,2758.06,2731.6,2699.9,8422.27537735],[1501545600,2676.01,2925,2856.89,2732.59,9772.96947501],[1501459200,2700,2900,2723.99,2856.88,11462.1802407],[1501372800,2500,2739.98,2700.2,2723.99,8460.182768],[1501286400,2656,2790.99,2786.07,2700.21,9860.13224068],[1501200000,2655.55,2825.11,2664.99,2786.07,17189.24674204],[1501113600,2514.1,2686.2,2525.98,2664.99,10034.52706572],[1501027200,2403,2614,2564,2525.99,13019.03454142],[1500940800,2449.69,2782.44,2761.68,2564,19195.82260736],[1500854400,2726.8,2799.2,2755.19,2762.26,8105.64511248],[1500768000,2691,2848,2825.27,2754.28,10194.97475019],[1500681600,2646.95,2869.88,2661.05,2825.27,12225.61763679],[1500595200,2608.27,2880,2873.45,2657.45,23062.18542954],[1500508800,2258.99,2957,2258.99,2873.48,36509.30587417],[1500422400,2216,2396,2307.48,2258.99,18567.47611252],[1500336000,2134.37,2393.43,2235.14,2308.15,23795.59414253],[1500249600,1909.58,2238.07,1911.79,2235.19,21436.7645371],[1500163200,1758.2,2043.94,1964.33,1911.78,21740.89274035],[1500076800,1964.31,2224.82,2217.02,1964.31,16334.68864717],[1499990400,2150,2349.28,2340,2217.24,13549.1778099],[1499904000,2308.14,2416.79,2384.35,2340,9541.53943311],[1499817600,2250,2415,2310,2383.42,13834.47197463],[1499731200,2265,2410,2330.93,2310.01,15670.55064724],[1499644800,2250,2523,2508,2331.05,15554.0050949],[1499558400,2500,2579.84,2560.84,2508.99,5647.43426949],[1499472000,2471.22,2563.5,2501.15,2561.11,7869.88131277],[1499385600,2472,2607.61,2604.89,2501.15,11640.78157115],[1499299200,2580.69,2623.54,2616.96,2604.84,8207.99657687],[1499212800,2551.06,2630.24,2602,2616.96,10183.63010323],[1499126400,2542.18,2636.1,2542.41,2602,10680.56522172],[1499040000,2479.75,2584.78,2515.37,2542.41,10045.8328211],[1498953600,2385,2545,2424.08,2516.66,9098.28919886],[1498867200,2400,2515,2455.19,2423.63,8448.08879856],[1498780800,2446.2,2554.01,2531.16,2455.19,11860.9594359],[1498694400,2506.1,2591.98,2553.13,2530,9048.16102048],[1498608000,2457,2605,2573.22,2553.12,16240.95462101],[1498521600,2264,2575.75,2407.91,2575.75,22151.51962082],[1498435200,2258.34,2563.9,2505.61,2407.91,20262.76215295],[1498348800,2430.05,2625,2574.86,2505.61,13739.17133582],[1498262400,2503.05,2718.37,2690.76,2574.84,12808.47796498],[1498176000,2665,2743,2679.93,2690.76,9674.14014661],[1498089600,2598,2724.69,2643.33,2679.99,12179.55378226],[1498003200,2559.51,2781.59,2725.11,2643.35,18065.09195302],[1497916800,2585.42,2776.95,2596.99,2725.08,19230.12622071],[1497830400,2481.92,2597,2515.25,2596.98,13928.55868512],[1497744000,2455.01,2670,2634.94,2515.25,13831.60864849],[1497657600,2413.96,2679.24,2480.44,2634.94,17601.3141096],[1497571200,2287.84,2524.65,2409.98,2480.43,21891.95771822],[1497484800,2050,2525,2432.21,2409.98,42025.04188091],[1497398400,2330,2827,2709.02,2432.21,28257.13485767],[1497312000,2649.47,2798.99,2654.36,2709.01,19716.97419151],[1497225600,2463.89,2999.99,2998.98,2655.71,38941.18214331],[1497139200,2881,2998.99,2931.16,2998.98,16295.4930364],[1497052800,2801.25,2942.04,2811.37,2931.15,18734.85190549],[1496966400,2786.2,2861.58,2799.76,2811.39,11440.33561555],[1496880000,2611.41,2808.78,2690.02,2799.73,13453.68915971],[1496793600,2598.7,2885,2871.29,2685.64,19476.18369094],[1496707200,2674.69,2938.55,2698,2871.29,28609.64698371],[1496620800,2517.02,2698,2521.43,2698,13599.76890434],[1496534400,2469.98,2556.1,2548.3,2521.36,13820.79309963],[1496448000,2448,2599,2478.99,2548.05,13441.88879769],[1496361600,2379.44,2478.99,2419.98,2478.99,12890.65884371],[1496275200,2302,2488,2303.61,2419.99,21390.33504326],[1496188800,2173.8,2338.91,2191.6,2303.29,21726.930856],[1496102400,2112.31,2336.88,2279.18,2191.58,20915.9999948],[1496016000,2141.12,2357.86,2237,2279.48,16926.34457276],[1495929600,2099.86,2342.99,2099.99,2232.78,18342.68197108],[1495843200,1913.19,2353.35,2276.46,2099.99,32466.17123427],[1495756800,2052.01,2683.18,2362.17,2272.7,31755.902624],[1495670400,2226.86,2806,2432.96,2355,37194.83761353],[1495584000,2266.51,2474.69,2272.74,2432.97,24659.73425375],[1495497600,2100.86,2283,2123.29,2272.75,17640.94851589],[1495411200,1975,2298,2056.99,2123.29,29431.53634619],[1495324800,1988.6,2102.68,2058.89,2057,17762.48439112],[1495238400,1970.04,2059,1976.22,2058.91,13176.28271359],[1495152000,1890.73,1980,1899.47,1976.23,18971.77074076],[1495065600,1800,1900,1813.23,1899.16,11391.00937384],[1494979200,1745.05,1840,1777.49,1813.23,13813.22143771],[1494892800,1690.14,1777.76,1747.81,1777.48,11414.50874225],[1494806400,1702.42,1802.99,1799.98,1747.81,10191.85424893],[1494720000,1763.33,1829,1791.7,1799.99,6806.48511914],[1494633600,1610,1792.96,1695.56,1792.73,12379.99373457],[1494547200,1651.01,1838,1837.98,1695.61,16527.80375242],[1494460800,1770.95,1889,1794.95,1837.93,15726.10460336],[1494374400,1691.3,1799.99,1720.24,1794.99,13458.24717656],[1494288000,1630,1794.7,1712.99,1720.43,19878.9688314],[1494201600,1608,1713,1611.1,1713,15894.92006435],[1494115200,1563.87,1618.31,1585.49,1609.57,11737.5699792],[1494028800,1551.3,1598.89,1551.3,1585.39,9367.70501254],[1493942400,1535.11,1630,1561.47,1551.3,16888.18805884],[1493856000,1482.06,1665,1533,1563.39,26721.20592273],[1493769600,1453.68,1533,1471.79,1533,16319.00509692],[1493683200,1426.51,1492.93,1436.5,1471.99,12031.58419061],[1493596800,1370.98,1466.69,1384.55,1436.5,16992.30099696],[1493510400,1334.02,1394.51,1364.98,1384.55,10543.183517],[1493424000,1335.64,1369.5,1352.96,1365.43,9669.26577868],[1493337600,1300.2,1381.01,1349.77,1353.34,14008.47741677],[1493251200,1295.39,1360,1297.56,1349.26,10484.92361594],[1493164800,1279.5,1320,1281.18,1298.44,9597.58080942],[1493078400,1256.16,1287,1256.65,1281.16,8117.86793375],[1492992000,1246.31,1261.16,1251.91,1257.29,5906.25903817],[1492905600,1236.2,1254,1246.79,1251.98,5023.52597801],[1492819200,1221.51,1253,1249.98,1247,6147.34768133],[1492732800,1236.15,1258.77,1236.15,1249.99,6669.14516894],[1492646400,1212.01,1240.6,1214.22,1236.15,7747.22509693],[1492560000,1191.09,1215.32,1201.88,1214.21,6273.61537614],[1492473600,1189.76,1206.65,1190.95,1201.94,6269.90926487],[1492387200,1170.85,1197.6,1177.63,1189.91,6548.06656297],[1492300800,1171.7,1189.93,1178.84,1177.99,3084.52503854],[1492214400,0.06,1190.99,1173.13,1178.85,3972.00314582],[1492128000,1170.14,1196.92,1177.05,1173.74,5666.3149436],[1492041600,1148.98,1219.49,1214.68,1177.05,9426.5374569],[1491955200,1209.61,1227.86,1224,1214.17,6494.15156162],[1491868800,1200,1234,1210,1223.99,5481.08329834],[1491782400,1201,1219.78,1210.99,1210,5644.96147616],[1491696000,1175.8,1221,1184.5,1210.97,5819.87128162],[1491609600,1170,1198,1194,1184.5,4423.10758142],[1491523200,1175.26,1203,1192.29,1194,6984.36797928],[1491436800,1132.98,1206.97,1132.99,1192.3,11233.49672084],[1491350400,1114.9,1144.99,1143.98,1132.99,8705.92018413],[1491264000,1124.98,1164.14,1152.09,1143.99,8960.55337266],[1491177600,1112.24,1168.72,1113.23,1152.6,12694.07860904],[1491091200,1080,1119,1092,1113.99,7882.35425504],[1491004800,1071.45,1110.95,1088.99,1092,6726.97042802],[1490918400,1038.11,1094.49,1042.32,1088.99,11274.0990776],[1490832000,1022,1052.94,1043.09,1042.34,8312.81365608],[1490745600,1005.77,1058.16,1045.54,1043.27,8676.30276913],[1490659200,1016.25,1069.39,1042.27,1045.4,9055.35196409],[1490572800,961.1,1045.9,973.97,1042.08,10235.89059265],[1490486400,943.9,1005,963.72,973.08,9504.75859053],[1490400000,890.05,973.99,933.93,963.72,16665.09971431],[1490313600,920.1,1030.3,1025.13,934.87,19003.40525575],[1490227200,1013,1057.41,1038.94,1025.14,7782.58744987],[1490140800,985.17,1114.96,1114.42,1034.57,14577.910023502238],[1490054400,1042.68,1120,1046.75,1114.42,12493.158303386517],[1489968000,1011,1051.97,1019.1,1044.96,8919.41542151],[1489881600,961.59,1062.92,970,1019.49,13518.38951375],[1489795200,919.44,1096,1068.78,970,23968.77126486],[1489708800,1065.74,1175.11,1175.11,1069.57,19222.89558418],[1489622400,1117.77,1277.27,1263.55,1175.11,16599.28971021],[1489536000,1240,1264.55,1247.43,1263,7273.3089643],[1489449600,1213.55,1262,1245.5,1247.42,7464.25969536],[1489363200,1206,1249,1235.27,1245.49,9584.41601345],[1489276800,1150,1244,1188.11,1235.58,6729.15133551],[1489190400,1107,1219,1111.92,1188.11,10281.23814954],[1489104000,956.85,1360,1197.3,1109.01,25699.70747898],[1489017600,1131.11,1214.95,1150.22,1197.3,8524.46513332],[1488931200,1128,1246,1237.36,1150.22,13024.97292998],[1488844800,1050,1288,1284.99,1237.36,10811.13480336],[1488758400,1268.78,1288,1278.63,1284.99,4763.57331155],[1488672000,1247.11,1278.99,1273.94,1278.98,3996.81717973],[1488585600,1226.41,1294.48,1293.06,1273.97,6385.03090633],[1488499200,1255.61,1294.99,1269.17,1292.86,8290.63821009],[1488412800,1220,1298.61,1230,1269.17,8940.28335112],[1488326400,1085.71,1230,1194.53,1230,8122.93568298],[1488240000,1179.64,1214.94,1195.84,1195.08,6720.38236942],[1488153600,1176,1198.99,1184.91,1195.81,5776.45621667],[1488067200,1130.88,1187.33,1157.98,1184.91,4454.44399496],[1487980800,1110,1189.49,1186.91,1158,6033.90242829],[1487894400,1103.32,1221.93,1185.81,1186.91,12746.94744846],[1487808000,1128.22,1197,1129.87,1186.9,7574.4599592],[1487721600,1104.9,1140,1129.67,1128.71,6035.82346759],[1487635200,1081.95,1132.95,1089.98,1128.29,7487.52401771],[1487548800,1051.36,1095,1059.88,1089.82,4434.4419852],[1487462400,1051.26,1067.78,1062.14,1059.88,3025.41424506],[1487376000,1055.6,1073.8,1057.29,1062.15,3934.74788542],[1487289600,1036.29,1064.6,1038.95,1057.3,6334.69845378],[1487203200,1013.02,1041.88,1014.58,1038.94,5996.29323251],[1487116800,1007.66,1016,1013.92,1014.53,4494.35016842],[1487030400,992.27,1018.97,1002.88,1013.92,5910.49032795],[1486944000,985.68,1021.5,1009.99,1002.82,4721.75058283],[1486857600,1008,1018.88,1018.63,1010,1315.7295579],[1486771200,995.49,1023.89,1001.88,1018.65,4321.97059564],[1486684800,961,1008,993.58,1001.99,7943.72633682],[1486598400,925,1079,1057.22,994.24,16569.65090403],[1486512000,1016.49,1069.95,1053.95,1056.7,6979.97233106],[1486425600,1021.75,1058.26,1022.65,1053.96,5492.40880901],[1486339200,1014.64,1027.7,1016.32,1022.58,4367.25829503],[1486252800,1003.02,1036.3,1035.54,1016.32,4621.39169086],[1486166400,1001.8,1044.12,1018.48,1035.54,4793.80522616],[1486080000,994.34,1024.5,1008.4,1018,6776.26971846],[1485993600,978.74,1010,992.75,1008.38,5728.21238077],[1485907200,963.84,992.75,970.01,992.75,5993.62596645],[1485820800,922.94,972.3,923.26,970.01,6733.34318664],[1485734400,914.69,923.95,916.56,923.23,3622.27666203],[1485648000,915,927.47,924.69,916.54,2592.34365375],[1485561600,921.81,925.5,922.89,924.98,2634.53799739],[1485475200,911,924.47,917.02,922.63,3719.06548579],[1485388800,896,921.95,896.75,917.02,4718.08253344],[1485302400,886.99,903.98,887,896,4535.10457614],[1485216000,880,923,911.78,887,6401.73515269],[1485129600,910.63,931.33,929.45,910.7,4142.93227389],[1485043200,902,946.25,925.06,931.22,5044.15354801],[1484956800,891.28,930,894.31,925.06,4666.66088887],[1484870400,890,904.59,902.92,894.31,3110.58974194],[1484784000,883.08,907,887.98,902.92,5070.18463001],[1484697600,850,916.7,906.09,887.99,6937.98652365],[1484611200,830.1,909,834.4,906,7253.4885706],[1484524800,826.03,840,833.43,834.41,3428.89193045],[1484438400,819,835,828,833.31,2941.91504862],[1484352000,822.34,847.52,831.42,828,4774.33377561],[1484265600,782.85,835.01,812.25,831.42,10492.67371002],[1484179200,734.64,840,795.8,812.25,13200.46287512],[1484092800,765,923.98,906.81,795.77,19443.63528428],[1484006400,899.01,915.1,902.66,907,7226.04044665],[1483920000,886.42,923.58,922.04,902.66,5909.57812167],[1483833600,899.16,953.8,908.99,923.33,5410.00349909],[1483747200,802.07,910,895.78,909,11217.17862761],[1483660800,875.01,1033.85,1007,895.71,14274.25920626],[1483574400,880,1175,1131.1,1007,20446.40561546],[1483488000,1018,1147,1020.69,1130.3,16222.23026666],[1483401600,1006.71,1036.99,1011.52,1020.67,8615.26005814],[1483315200,990.52,1034.39,992.96,1011.45,7723.63575162]]